#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob

APP = ['OnlineClass.pyw']
DATA_FILES = [('images', glob.glob('images/*.*')), ('data', glob.glob('data/*.*')), 'LICENSE.txt', 'VERSION.txt']
OPTIONS = {
    'iconfile':'images/OCH_Logo.icns',
    'argv_emulation': False,
    'plist': {
        'CFBundleName': 'OCH',
        'CFBundleDisplayName': 'OCH',
        'CFBundleIdentifier': "com.ravens.osx.OCH",
        'CFBundleVersion': "1.1.0",
        'CFBundleShortVersionString': "1.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2021, Ravens Enterprises, All Rights Reserved"
    },
    'includes': ['requests', 'PIL', 'tkinter', 'tk']
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
